# Generated by Django 2.0 on 2020-10-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201014_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
